### ISSUE TITLE
Expecting two different outcomes

### ISSUE THREAD

**Issue by briankil** [learn-co-curriculum/reverse-each-word#10]
1st Test inputs "Hello there, and how are you?" and expects "olleH *,ereht* dna woh era ?uoy"
2nd Test inputs "Hi again, just making sure it's reversed!" and expects "iH *niaga,* tsuj gnikam erus s'ti !desrever"

The comma in the first test is reversed but the comma in the second test remains at the end of the word. Two inconsistent expectations.

**Comment by AnnJohn** [comment]
Thanks, fixed the second test.
