### ISSUE TITLE
Reverse Each Word - Possible Test Typo

### ISSUE THREAD

**Issue by magfurulabeer** [learn-co-curriculum/reverse-each-word#11]
I believe that there was an error in the specification file. In the second test, 
"again," reversed is "niaga," 
with the comma at the end unaffected from the reverse method while in the first test,
"there," reversed  was ",ereht". 
affected by the reverse. Not noticing a reasoning behind this, I assumed it was a typo
and ended up changing the second test so that "niaga," was ",niaga".

If I missed something, please let me know and I will change the test back and attempt the
lab again.

**Comment by AnnJohn** [comment]
Thanks, we fixed the issue.
