### ISSUE TITLE
rspec issue

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/reverse-each-word#13]
The rspec's second test for this lesson seems to have an issue. 

It requires the code to produce words in reverse order. The argument the rspec passes is: "Hi again, just making sure it's reversed!" The expected string is: "iH niaga, tsuj gnikam erus s'ti !desrever". As you can see, the last word in the string reversed with the punctuation included ("reversed!" -> "!desrever"), but the second word didn't ("again," -> "niaga,"). 

The correct output requirement should be "iH ,niaga tsuj gnikam erus s'ti !desrever".

**Comment by AnnJohn** [comment]
Thanks for raising the issue, corrected the test suite.
