### ISSUE TITLE
Following code-along won't pass test.

### ISSUE THREAD

**Issue by chemturion** [learn-co-curriculum/reverse-each-word#17]
Prior to starting the Advanced section, the lab states:

> Here, we tell our method to return the original array simply by having that array be the last line of the method. Whatever is evaluated last in a method will be it's return value. **If you run the test again, you should be passing.**

The original array contains "Jim", so how can returning the original array possibly pass the tests, which expect only strings beginning with "T" to be returned?

**Comment by Joll59** [comment]
@chemturion Thank you for submitting issue, I believe you've submitted this issue on the wrong repo/lab. If you are still having any problems with this lab please utilize Learn.co Ask A Question feature or join the slack channel and ask. 

Closing issue for now.
