### ISSUE TITLE
Confusing readme with enumerating .each AND .collect

### ISSUE THREAD

**Issue by dsound-zz** [learn-co-curriculum/reverse-each-word#18]
I'm a newb so it was confusing to realize that after passing the tests with .each, I can use the same method with .collect and still have the tests pass. Wasn't sure if I had to create a second method or try to implement .each and .collect in the same method. 

Thanks.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
