### ISSUE TITLE
Issue with 'reverses all words in string w/o reversing order" spec

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/reverse-each-word#9]
Hey,

looks like there might be an issue with the 2nd spec for this lab.

I used the solution provided in the solution branch and got the following error:

```
expected: "iH niaga, tsuj gnikam erus s'ti !desrever"
            got: "iH ,niaga tsuj gnikam erus s'ti !desrever"
```

The first spec has the comma reverse as part of the word.  The second spec has the word reverse but the comma stay in place.  There's no way for both of these two pass using the same method.

Suggest updating second spec to:

```ruby
describe '#reverse_each_word' do
  let(:sentence2) { "Hi again, just making sure it's reversed!" }
  it 'reverses all the words in a string without reversing the order of the words' do
    expect(reverse_each_word(sentence2)).to eq("iH ,niaga tsuj gnikam erus s'ti !desrever")
  end
end
```

**Comment by AnnJohn** [comment]
@danny-sullivan can you look into this?

**Comment by seemajune** [comment]
@danny-sullivan i submitted a PR simple fix if you want to review

**Comment by AnnJohn** [comment]
Thanks @seemajune. Merged the PR.
